<?php

/**
 * Name : PHPemojidata
 * Author : Amir Shokri
 * Date : 15 October 2021
 * Email : amirsh.nll@gmail.com
 */

class PHPemojidata {
	public $glass							= "\uf000";
	public $music							= "\uf001";
	public $search							= "\uf002";
	public $envelopeoutlined				= "\uf003";
	public $heart							= "\uf004";
	public $star							= "\uf005";
	public $staroutlined					= "\uf006";
	public $user							= "\uf007";
	public $film							= "\uf008";
	public $thlarge							= "\uf009";
	public $th								= "\uf00a";
	public $thlist							= "\uf00b";
	public $check							= "\uf00c";
	public $times							= "\uf00d";
	public $searchplus						= "\uf00e";
	public $searchmnus						= "\uf010";
	public $poweroff						= "\uf011";
	public $signal							= "\uf012";
	public $cog								= "\uf013";
	public $trashoutlined					= "\uf014";
	public $home							= "\uf015";
	public $fileoutlined					= "\uf016";
	public $clockoutlined					= "\uf017";
	public $road							= "\uf018";
	public $download						= "\uf019";
	public $arrowcircleoutlineddown			= "\uf01a";
	public $arrowcircleoutlinedup			= "\uf01b";
	public $inbox							= "\uf01c";
	public $playcircleoutlined				= "\uf01d";
	public $repeat							= "\uf01e";
	public $refresh							= "\uf021";
	public $listalt							= "\uf022";
	public $lock							= "\uf023";
	public $flag							= "\uf024";
	public $headphones						= "\uf025";
	public $volumeoff						= "\uf026";
	public $volumedown						= "\uf027";
	public $volumeup						= "\uf028";
	public $qrcode							= "\uf029";
	public $barcode							= "\uf02a";
	public $tag								= "\uf02b";
	public $tags							= "\uf02c";
	public $book							= "\uf02d";
	public $bookmark						= "\uf02e";
	public $printemoji						= "\uf02f";
	public $camera							= "\uf030";
	public $font							= "\uf031";
	public $bold							= "\uf032";
	public $italic							= "\uf033";
	public $textheight						= "\uf034";
	public $textwidth						= "\uf035";
	public $alignleft						= "\uf036";
	public $aligncenter						= "\uf037";
	public $alignright						= "\uf038";
	public $alignjustify					= "\uf039";
	public $list							= "\uf03a";
	public $outdent							= "\uf03b";
	public $indent							= "\uf03c";
	public $videocamera						= "\uf03d";
	public $picture							= "\uf03e";
	public $pencil							= "\uf040";
	public $mapmarker						= "\uf041";
	public $adjust							= "\uf042";
	public $tint							= "\uf043";
	public $pencilsquareoutlined			= "\uf044";
	public $sharesquareoutlined				= "\uf045";
	public $checksquareoutlined				= "\uf046";
	public $arrows							= "\uf047";
	public $stepbackward					= "\uf048";
	public $fastbackward					= "\uf049";
	public $backward						= "\uf04a";
	public $play							= "\uf04b";
	public $pause							= "\uf04c";
	public $stop							= "\uf04d";
	public $forward							= "\uf04e";
	public $fastforward						= "\uf050";
	public $stepforward						= "\uf051";
	public $eject							= "\uf052";
	public $chevronleft						= "\uf053";
	public $chevronright					= "\uf054";
	public $pluscircle						= "\uf055";
	public $minuscircle						= "\uf056";
	public $timescircle						= "\uf057";
	public $checkcircle						= "\uf058";
	public $questioncircle					= "\uf059";
	public $infocircle						= "\uf05a";
	public $timescircleoutlined				= "\uf05c";
	public $checkcircleoutlined				= "\uf05d";
	public $ban								= "\uf05e";
	public $arrowleft						= "\uf060";
	public $arrowright						= "\uf061";
	public $arrowup							= "\uf062";
	public $arrowdown						= "\uf063";
	public $share							= "\uf064";
	public $expand							= "\uf065";
	public $compress						= "\uf066";
	public $plus							= "\uf067";
	public $minus							= "\uf068";
	public $asterisk						= "\uf069";
	public $exclamationcircle				= "\uf06a";
	public $gift							= "\uf06b";
	public $leaf							= "\uf06c";
	public $fire							= "\uf06d";
	public $eye								= "\uf06e";
	public $eyeslash						= "\uf070";
	public $exclamationtriangle				= "\uf071";
	public $plane							= "\uf072";
	public $calendar						= "\uf073";
	public $random							= "\uf074";
	public $comment							= "\uf075";
	public $magnet							= "\uf076";
	public $chevronup						= "\uf077";
	public $chevrondown						= "\uf078";
	public $retweet							= "\uf079";
	public $shoppingcart					= "\uf07a";
	public $folder							= "\uf07b";
	public $folderopen						= "\uf07c";
	public $arrowsvertical					= "\uf07d";
	public $arrowshorizontal				= "\uf07e";
	public $barchart						= "\uf080";
	public $twittersquare					= "\uf081";
	public $facebooksquare					= "\uf082";
	public $cameraretro						= "\uf083";
	public $key								= "\uf084";
	public $cogs							= "\uf085";
	public $comments						= "\uf086";
	public $thumbsupoutlined				= "\uf087";
	public $thumbsdownoutlined				= "\uf088";
	public $starhalf						= "\uf089";
	public $heartoutlined					= "\uf08a";
	public $signout							= "\uf08b";
	public $linkedinsquare					= "\uf08c";
	public $thumbtack						= "\uf08d";
	public $externallink					= "\uf08e";
	public $signin							= "\uf090";
	public $trophy							= "\uf091";
	public $githubsquare					= "\uf092";
	public $upload							= "\uf093";
	public $lemonoutlined					= "\uf094";
	public $phone							= "\uf095";
	public $squareoutlined					= "\uf096";
	public $bookmarkoutlined				= "\uf097";
	public $phonesquare						= "\uf098";
	public $twitter							= "\uf099";
	public $facebook						= "\uf09a";
	public $github							= "\uf09b";
	public $unlock							= "\uf09c";
	public $creditcard						= "\uf09d";
	public $rss								= "\uf09e";
	public $hdd								= "\uf0a0";
	public $bullhorn						= "\uf0a1";
	public $bell							= "\uf0a2";
	public $certificate						= "\uf0a3";
	public $handoutlinedright				= "\uf0a4";
	public $handoutlinedleft				= "\uf0a5";
	public $handoutlinedup					= "\uf0a6";
	public $handoutlineddown				= "\uf0a7";
	public $arrowcircleleft					= "\uf0a8";
	public $arrowcircleright				= "\uf0a9";
	public $arrowcircleup					= "\uf0aa";
	public $arrowcircledown					= "\uf0ab";
	public $globe							= "\uf0ac";
	public $wrench							= "\uf0ad";
	public $tasks							= "\uf0ae";
	public $filter							= "\uf0b0";
	public $briefcase						= "\uf0b1";
	public $arrowsalt						= "\uf0b2";
	public $users							= "\uf0c0";
	public $link							= "\uf0c1";
	public $cloud							= "\uf0c2";
	public $flask							= "\uf0c3";
	public $scissors						= "\uf0c4";
	public $filesoutlined					= "\uf0c5";
	public $paperclip						= "\uf0c6";
	public $floppyoutlined					= "\uf0c7";
	public $square							= "\uf0c8";
	public $bars							= "\uf0c9";
	public $listul							= "\uf0ca";
	public $listol							= "\uf0cb";
	public $strikethrough					= "\uf0cc";
	public $underline						= "\uf0cd";
	public $table							= "\uf0ce";
	public $magic							= "\uf0d0";
	public $truck							= "\uf0d1";
	public $pinterest						= "\uf0d2";
	public $pinterestsquare					= "\uf0d3";
	public $googleplussquare				= "\uf0d4";
	public $googleplus						= "\uf0d5";
	public $money							= "\uf0d6";
	public $caretdown						= "\ud0d7";
	public $caretup							= "\uf0d8";
	public $caretleft						= "\uf0d9";
	public $caretright						= "\uf0da";
	public $columns							= "\uf0db";
	public $sort							= "\uf0dc";
	public $sortdescending					= "\uf0dd";
	public $sortascending					= "\uf0de";
	public $envelope						= "\uf0e0";
	public $linkedin						= "\uf0e1";
	public $undo							= "\uf0e2";
	public $gavel							= "\uf0e3";
	public $tachometer						= "\uf0e4";
	public $commento						= "\uf0e5";
	public $commentso						= "\uf0e6";
	public $lightningbolt					= "\uf0e7";
	public $sitemap							= "\uf0e8";
	public $umbrella						= "\uf0e9";
	public $clipboard						= "\uf0ea";
	public $lightbulboutlined				= "\uf0eb";
	public $exchange						= "\uf0ec";
	public $clouddownload					= "\uf0ed";
	public $cloudupload						= "\uf0ee";
	public $usermd							= "\uf0f0";
	public $stethoscope						= "\uf0f1";
	public $suitcase						= "\uf0f2";
	public $belloutlined					= "\uf0a2";
	public $coffee							= "\uf0f4";
	public $cutlery							= "\uf0f5";
	public $filetextoutlined				= "\uf0f6";
	public $buildingoutlined				= "\uf0f7";
	public $hospitaloutlined				= "\uf0f8";
	public $ambulance						= "\uf0f9";
	public $medkit							= "\uf0fa";
	public $fighterjet						= "\uf0fb";
	public $beer							= "\uf0fc";
	public $hsquare							= "\uf0fd";
	public $plussquare						= "\uf0fe";
	public $angledoubleleft					= "\uf100";
	public $angledoubleright				= "\uf101";
	public $angledoubleup					= "\uf102";
	public $angledoubledown					= "\uf103";
	public $angleleft						= "\uf104";
	public $angleright						= "\uf105";
	public $angleup							= "\uf106";
	public $angledown						= "\uf107";
	public $desktop							= "\uf108";
	public $laptop							= "\uf109";
	public $tablet							= "\uf10a";
	public $mobilephone						= "\uf10b";
	public $circleoutlined					= "\uf10c";
	public $quoteleft						= "\uf10d";
	public $quoteright						= "\uf10e";
	public $spinner							= "\uf110";
	public $circle							= "\uf111";
	public $reply							= "\uf112";
	public $githubalt						= "\uf113";
	public $folderoutlined					= "\uf114";
	public $folderopenoutlined				= "\uf115";
	public $smileoutlined					= "\uf118";
	public $frownoutlined					= "\uf119";
	public $mehoutlined						= "\uf11a";
	public $gamepad							= "\uf11b";
	public $keyboardoutlined				= "\uf11c";
	public $flagoutlined					= "\uf11d";
	public $flagcheckered					= "\uf11e";
	public $terminal						= "\uf120";
	public $code							= "\uf121";
	public $replyall						= "\uf122";
	public $starhalfoutlined				= "\uf123";
	public $locationarrow					= "\uf124";
	public $crop							= "\uf125";
	public $codefork						= "\uf126";
	public $chainbroken						= "\uf127";
	public $question						= "\uf128";
	public $info							= "\uf129";
	public $exclamation						= "\uf12a";
	public $superscript						= "\uf12b";
	public $subscript						= "\uf12c";
	public $eraser							= "\uf12d";
	public $puzzlepiece						= "\uf12e";
	public $microphone						= "\uf130";
	public $microphoneslash					= "\uf131";
	public $shield							= "\uf132";
	public $calendero						= "\uf133";
	public $fireextinguisher				= "\uf134";
	public $rocket							= "\uf135";
	public $maxcdn							= "\uf136";
	public $chevroncircleleft				= "\uf137";
	public $chevroncircleright				= "\uf138";
	public $chevroncircleup					= "\uf139";
	public $chevroncircledown				= "\uf13a";
	public $html5logo						= "\uf13b";
	public $css3logo						= "\uf13c";
	public $anchor							= "\uf13d";
	public $unlockalt						= "\uf13e";
	public $bullseye						= "\uf140";
	public $ellipsishorizontal				= "\uf141";
	public $ellipsisvertical				= "\uf142";
	public $rsssquare						= "\uf143";
	public $playcircle						= "\uf144";
	public $ticket							= "\uf145";
	public $minussquare						= "\uf146";
	public $minussquareoutlined				= "\uf147";
	public $levelup							= "\uf148";
	public $leveldown						= "\uf149";
	public $checksquare						= "\uf14a";
	public $pencilsquare					= "\uf14b";
	public $externallinksquare				= "\uf14c";
	public $sharesquare						= "\uf14d";
	public $compass							= "\uf14e";
	public $caretsquareoutlineddown			= "\uf150";
	public $caretsquareoutlinedup			= "\uf151";
	public $caretsquareoutlinedright		= "\uf152";
	public $euro							= "\uf153";
	public $gbp								= "\uf154";
	public $usdollar						= "\uf155";
	public $indianrupee						= "\uf156";
	public $japaneseyen						= "\uf157";
	public $russianruble					= "\uf158";
	public $koreanwon						= "\uf159";
	public $bitcoin							= "\uf15a";
	public $file							= "\uf15b";
	public $filetext						= "\uf15c";
	public $sortalphaascending				= "\uf15d";
	public $sortalphadescending				= "\uf15e";
	public $sortamountascending				= "\uf160";
	public $sortamountdescending			= "\uf161";
	public $sortnumericascending			= "\uf162";
	public $sortnumericdescending			= "\uf163";
	public $thumbsup						= "\uf164";
	public $thumbsdown						= "\uf165";
	public $youtubesquare					= "\uf166";
	public $youtube							= "\uf167";
	public $xing							= "\uf168";
	public $xingsquare						= "\uf169";
	public $youtubeplay						= "\uf16a";
	public $dropbox							= "\uf16b";
	public $stackoverflow					= "\uf16c";
	public $instagram						= "\uf16d";
	public $flickr							= "\uf16e";
	public $appdotnet						= "\uf170";
	public $bitbucket						= "\uf171";
	public $bitbucketsquare					= "\uf172";
	public $tumblr							= "\uf173";
	public $tumblrsquare					= "\uf174";
	public $longarrowdown					= "\uf175";
	public $longarrowup						= "\uf176";
	public $longarrowleft					= "\uf177";
	public $longarrowright					= "\uf178";
	public $apple							= "\uf179";
	public $windows							= "\uf17a";
	public $android							= "\uf17b";
	public $linux							= "\uf17c";
	public $dribbble						= "\uf17d";
	public $skype							= "\uf17e";
	public $foursquare						= "\uf180";
	public $trello							= "\uf181";
	public $female							= "\uf182";
	public $male							= "\uf183";
	public $gratipay						= "\uf184";
	public $sunoutlined						= "\uf185";
	public $moonoutlined					= "\uf186";
	public $archive							= "\uf187";
	public $bug								= "\uf188";
	public $vk								= "\uf189";
	public $weibo							= "\uf18a";
	public $renren							= "\uf18b";
	public $pagelines						= "\uf18c";
	public $stackexchange					= "\uf18d";
	public $arrowcircleoutlinedright		= "\uf18e";
	public $arrowcircleoutlinedleft			= "\uf190";
	public $caretsquareoutlinedleft			= "\uf191";
	public $dotcircleoutlined				= "\uf192";
	public $wheelchair						= "\uf193";
	public $vimeosquare						= "\uf194";
	public $turkishlira						= "\uf195";

	public $PHPemojistring = array(
		"Glass" 							=>	"\uf000",
		"Music" 							=>	"\uf001",
		"Search" 							=>	"\uf002",
		"EnvelopeOutlined" 					=>	"\uf003",
		"Heart" 							=>	"\uf004",
		"Star" 								=>	"\uf005",
		"StarOutlined" 						=>	"\uf006",
		"User" 								=>	"\uf007",
		"Film" 								=>	"\uf008",
		"ThLarge" 							=>	"\uf009",
		"Th" 								=>	"\uf00a",
		"ThList" 							=>	"\uf00b",
		"Check" 							=>	"\uf00c",
		"Times" 							=>	"\uf00d",
		"SearchPlus" 						=>	"\uf00e",
		"SearchMnus" 						=>	"\uf010",
		"PowerOff" 							=>	"\uf011",
		"Signal" 							=>	"\uf012",
		"Cog" 								=>	"\uf013",
		"TrashOutlined" 					=>	"\uf014",
		"Home" 								=>	"\uf015",
		"FileOutlined" 						=>	"\uf016",
		"ClockOutlined" 					=>	"\uf017",
		"Road" 								=>	"\uf018",
		"Download" 							=>	"\uf019",
		"ArrowCircleOutlinedDown" 			=>	"\uf01a",
		"ArrowCircleOutlinedUp" 			=>	"\uf01b",
		"Inbox" 							=>	"\uf01c",
		"PlayCircleOutlined" 				=>	"\uf01d",
		"Repeat" 							=>	"\uf01e",
		"Refresh" 							=>	"\uf021",
		"ListAlt" 							=>	"\uf022",
		"Lock" 								=>	"\uf023",
		"Flag" 								=>	"\uf024",
		"Headphones" 						=>	"\uf025",
		"VolumeOff" 						=>	"\uf026",
		"VolumeDown" 						=>	"\uf027",
		"VolumeUp" 							=>	"\uf028",
		"Qrcode" 							=>	"\uf029",
		"Barcode" 							=>	"\uf02a",
		"Tag" 								=>	"\uf02b",
		"Tags" 								=>	"\uf02c",
		"Book" 								=>	"\uf02d",
		"Bookmark" 							=>	"\uf02e",
		"PrintEmoji" 						=>	"\uf02f",
		"Camera" 							=>	"\uf030",
		"Font" 								=>	"\uf031",
		"Bold" 								=>	"\uf032",
		"Italic" 							=>	"\uf033",
		"TextHeight" 						=>	"\uf034",
		"TextWidth" 						=>	"\uf035",
		"AlignLeft" 						=>	"\uf036",
		"AlignCenter" 						=>	"\uf037",
		"AlignRight" 						=>	"\uf038",
		"AlignJustify" 						=>	"\uf039",
		"List" 								=>	"\uf03a",
		"Outdent" 							=>	"\uf03b",
		"Indent" 							=>	"\uf03c",
		"VideoCamera" 						=>	"\uf03d",
		"Picture" 							=>	"\uf03e",
		"Pencil" 							=>	"\uf040",
		"MapMarker" 						=>	"\uf041",
		"Adjust" 							=>	"\uf042",
		"Tint" 								=>	"\uf043",
		"PencilSquareOutlined" 				=>	"\uf044",
		"ShareSquareOutlined" 				=>	"\uf045",
		"CheckSquareOutlined" 				=>	"\uf046",
		"Arrows" 							=>	"\uf047",
		"StepBackward" 						=>	"\uf048",
		"FastBackward" 						=>	"\uf049",
		"Backward" 							=>	"\uf04a",
		"Play" 								=>	"\uf04b",
		"Pause" 							=>	"\uf04c",
		"Stop" 								=>	"\uf04d",
		"Forward" 							=>	"\uf04e",
		"FastForward" 						=>	"\uf050",
		"StepForward" 						=>	"\uf051",
		"Eject" 							=>	"\uf052",
		"ChevronLeft" 						=>	"\uf053",
		"ChevronRight" 						=>	"\uf054",
		"PlusCircle" 						=>	"\uf055",
		"MinusCircle" 						=>	"\uf056",
		"TimesCircle" 						=>	"\uf057",
		"CheckCircle" 						=>	"\uf058",
		"QuestionCircle" 					=>	"\uf059",
		"InfoCircle" 						=>	"\uf05a",
		"TimesCircleOutlined" 				=>	"\uf05c",
		"CheckCircleOutlined" 				=>	"\uf05d",
		"Ban" 								=>	"\uf05e",
		"ArrowLeft" 						=>	"\uf060",
		"ArrowRight" 						=>	"\uf061",
		"ArrowUp" 							=>	"\uf062",
		"ArrowDown" 						=>	"\uf063",
		"Share" 							=>	"\uf064",
		"Expand" 							=>	"\uf065",
		"Compress" 							=>	"\uf066",
		"Plus" 								=>	"\uf067",
		"Minus" 							=>	"\uf068",
		"Asterisk" 							=>	"\uf069",
		"ExclamationCircle" 				=>	"\uf06a",
		"Gift" 								=>	"\uf06b",
		"Leaf" 								=>	"\uf06c",
		"Fire" 								=>	"\uf06d",
		"Eye" 								=>	"\uf06e",
		"EyeSlash" 							=>	"\uf070",
		"ExclamationTriangle" 				=>	"\uf071",
		"Plane" 							=>	"\uf072",
		"Calendar" 							=>	"\uf073",
		"Random" 							=>	"\uf074",
		"Comment" 							=>	"\uf075",
		"Magnet" 							=>	"\uf076",
		"ChevronUp" 						=>	"\uf077",
		"ChevronDown" 						=>	"\uf078",
		"Retweet" 							=>	"\uf079",
		"ShoppingCart" 						=>	"\uf07a",
		"Folder" 							=>	"\uf07b",
		"FolderOpen" 						=>	"\uf07c",
		"ArrowsVertical" 					=>	"\uf07d",
		"ArrowsHorizontal" 					=>	"\uf07e",
		"BarChart" 							=>	"\uf080",
		"TwitterSquare" 					=>	"\uf081",
		"FacebookSquare" 					=>	"\uf082",
		"CameraRetro" 						=>	"\uf083",
		"Key" 								=>	"\uf084",
		"Cogs" 								=>	"\uf085",
		"Comments" 							=>	"\uf086",
		"ThumbsUpOutlined" 					=>	"\uf087",
		"ThumbsDownOutlined" 				=>	"\uf088",
		"StarHalf" 							=>	"\uf089",
		"HeartOutlined" 					=>	"\uf08a",
		"SignOut" 							=>	"\uf08b",
		"LinkedInSquare" 					=>	"\uf08c",
		"ThumbTack" 						=>	"\uf08d",
		"ExternalLink" 						=>	"\uf08e",
		"SignIn" 							=>	"\uf090",
		"Trophy" 							=>	"\uf091",
		"GitHubSquare" 						=>	"\uf092",
		"Upload" 							=>	"\uf093",
		"LemonOutlined" 					=>	"\uf094",
		"Phone" 							=>	"\uf095",
		"SquareOutlined" 					=>	"\uf096",
		"BookmarkOutlined" 					=>	"\uf097",
		"PhoneSquare" 						=>	"\uf098",
		"Twitter" 							=>	"\uf099",
		"Facebook" 							=>	"\uf09a",
		"GitHub" 							=>	"\uf09b",
		"Unlock" 							=>	"\uf09c",
		"CreditCard" 						=>	"\uf09d",
		"RSS" 								=>	"\uf09e",
		"HDD" 								=>	"\uf0a0",
		"Bullhorn" 							=>	"\uf0a1",
		"Bell" 								=>	"\uf0a2",
		"Certificate" 						=>	"\uf0a3",
		"HandOutlinedRight" 				=>	"\uf0a4",
		"HandOutlinedLeft" 					=>	"\uf0a5",
		"HandOutlinedUp" 					=>	"\uf0a6",
		"HandOutlinedDown" 					=>	"\uf0a7",
		"ArrowCircleLeft" 					=>	"\uf0a8",
		"ArrowCircleRight" 					=>	"\uf0a9",
		"ArrowCircleUp" 					=>	"\uf0aa",
		"ArrowCircleDown" 					=>	"\uf0ab",
		"Globe" 							=>	"\uf0ac",
		"Wrench" 							=>	"\uf0ad",
		"Tasks" 							=>	"\uf0ae",
		"Filter" 							=>	"\uf0b0",
		"Briefcase" 						=>	"\uf0b1",
		"ArrowsAlt" 						=>	"\uf0b2",
		"Users" 							=>	"\uf0c0",
		"Link" 								=>	"\uf0c1",
		"Cloud" 							=>	"\uf0c2",
		"Flask" 							=>	"\uf0c3",
		"Scissors" 							=>	"\uf0c4",
		"FilesOutlined" 					=>	"\uf0c5",
		"Paperclip" 						=>	"\uf0c6",
		"FloppyOutlined" 					=>	"\uf0c7",
		"Square" 							=>	"\uf0c8",
		"Bars" 								=>	"\uf0c9",
		"ListUl" 							=>	"\uf0ca",
		"ListOl" 							=>	"\uf0cb",
		"Strikethrough" 					=>	"\uf0cc",
		"Underline" 						=>	"\uf0cd",
		"Table" 							=>	"\uf0ce",
		"Magic" 							=>	"\uf0d0",
		"Truck" 							=>	"\uf0d1",
		"Pinterest" 						=>	"\uf0d2",
		"PinterestSquare" 					=>	"\uf0d3",
		"GooglePlusSquare" 					=>	"\uf0d4",
		"GooglePlus" 						=>	"\uf0d5",
		"Money" 							=>	"\uf0d6",
		"CaretDown" 						=>	"\ud0d7",
		"CaretUp" 							=>	"\uf0d8",
		"CaretLeft" 						=>	"\uf0d9",
		"CaretRight" 						=>	"\uf0da",
		"Columns" 							=>	"\uf0db",
		"Sort" 								=>	"\uf0dc",
		"SortDescending" 					=>	"\uf0dd",
		"SortAscending" 					=>	"\uf0de",
		"Envelope" 							=>	"\uf0e0",
		"LinkedIn" 							=>	"\uf0e1",
		"Undo" 								=>	"\uf0e2",
		"Gavel" 							=>	"\uf0e3",
		"Tachometer" 						=>	"\uf0e4",
		"CommentO" 							=>	"\uf0e5",
		"CommentsO" 						=>	"\uf0e6",
		"LightningBolt" 					=>	"\uf0e7",
		"Sitemap" 							=>	"\uf0e8",
		"Umbrella" 							=>	"\uf0e9",
		"Clipboard" 						=>	"\uf0ea",
		"LightbulbOutlined" 				=>	"\uf0eb",
		"Exchange" 							=>	"\uf0ec",
		"CloudDownload" 					=>	"\uf0ed",
		"CloudUpload" 						=>	"\uf0ee",
		"UserMd" 							=>	"\uf0f0",
		"Stethoscope" 						=>	"\uf0f1",
		"Suitcase" 							=>	"\uf0f2",
		"BellOutlined" 						=>	"\uf0a2",
		"Coffee" 							=>	"\uf0f4",
		"Cutlery" 							=>	"\uf0f5",
		"FileTextOutlined" 					=>	"\uf0f6",
		"BuildingOutlined" 					=>	"\uf0f7",
		"HospitalOutlined" 					=>	"\uf0f8",
		"Ambulance" 						=>	"\uf0f9",
		"Medkit" 							=>	"\uf0fa",
		"FighterJet" 						=>	"\uf0fb",
		"Beer" 								=>	"\uf0fc",
		"HSquare" 							=>	"\uf0fd",
		"PlusSquare" 						=>	"\uf0fe",
		"AngleDoubleLeft" 					=>	"\uf100",
		"AngleDoubleRight" 					=>	"\uf101",
		"AngleDoubleUp" 					=>	"\uf102",
		"AngleDoubleDown" 					=>	"\uf103",
		"AngleLeft" 						=>	"\uf104",
		"AngleRight" 						=>	"\uf105",
		"AngleUp" 							=>	"\uf106",
		"AngleDown" 						=>	"\uf107",
		"Desktop" 							=>	"\uf108",
		"Laptop" 							=>	"\uf109",
		"Tablet" 							=>	"\uf10a",
		"MobilePhone" 						=>	"\uf10b",
		"CircleOutlined" 					=>	"\uf10c",
		"QuoteLeft" 						=>	"\uf10d",
		"QuoteRight" 						=>	"\uf10e",
		"Spinner" 							=>	"\uf110",
		"Circle" 							=>	"\uf111",
		"Reply" 							=>	"\uf112",
		"GitHubAlt" 						=>	"\uf113",
		"FolderOutlined" 					=>	"\uf114",
		"FolderOpenOutlined" 				=>	"\uf115",
		"SmileOutlined" 					=>	"\uf118",
		"FrownOutlined" 					=>	"\uf119",
		"MehOutlined" 						=>	"\uf11a",
		"Gamepad" 							=>	"\uf11b",
		"KeyboardOutlined" 					=>	"\uf11c",
		"FlagOutlined" 						=>	"\uf11d",
		"FlagCheckered" 					=>	"\uf11e",
		"Terminal" 							=>	"\uf120",
		"Code" 								=>	"\uf121",
		"ReplyAll" 							=>	"\uf122",
		"StarHalfOutlined" 					=>	"\uf123",
		"LocationArrow" 					=>	"\uf124",
		"Crop" 								=>	"\uf125",
		"CodeFork" 							=>	"\uf126",
		"ChainBroken" 						=>	"\uf127",
		"Question" 							=>	"\uf128",
		"Info" 								=>	"\uf129",
		"Exclamation" 						=>	"\uf12a",
		"SuperScript" 						=>	"\uf12b",
		"SubScript" 						=>	"\uf12c",
		"Eraser" 							=>	"\uf12d",
		"PuzzlePiece" 						=>	"\uf12e",
		"Microphone" 						=>	"\uf130",
		"MicrophoneSlash" 					=>	"\uf131",
		"Shield" 							=>	"\uf132",
		"CalenderO" 						=>	"\uf133",
		"FireExtinguisher" 					=>	"\uf134",
		"Rocket" 							=>	"\uf135",
	);
}